[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://canteens-ffcmm.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, adminpin, AdminPin, admin-pin, Admin-Pin"
